#!/bin/sh
echo "Sending verification code via e-mail."
if test "$#" -lt 2; then
	echo "Not enough arguments passed to verification script."
	echo "The first argument should be the verification code and the second - phone number."
	exit 1
fi
if test "$#" -gt 2; then
	echo "Too many arguments passed to verification script."
	echo "The first argument should be the verification code and the second - phone number."
	exit 2 
fi
exit 0

